config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :todo_lists
  resources :campaigns
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'home#index'
  devise_scope :user do
    get 'users/:id/edit_status' => 'users/registrations#edit_status', as: :edit_user_status
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @novices = User.where(actable_type: 'Novice')
  end
end

app/views/home/_novice_users.html.erb
<div>
  <% @novices.each do |novice| %>
    <div>
      Username: <%= novice.username %>
      <ul>
        <li>Email: <%= novice.email %></li>
        <li>Status: <%= novice.status %></li>
        <%= link_to "Edit User Status", edit_user_status_path(novice) %>
      </ul>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Welcome to homify test app</h1>

<% if user_signed_in? %>
  <li>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>

    <% if can? :update, User %>
      <%= render 'novice_users' %>        
    <% end %>

    <% if can? :create, Campaign %>
      <%= link_to('Create Campaign', new_campaign_path, method: :get) %>
    <% end %>

    <br />
    <%= link_to('View Campaigns', campaigns_path, method: :get) %>
  </li>
  
<% else %>
  <li>
    <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>