config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :todo_lists
  resources :campaigns
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'home#index'
  devise_scope :user do
    get 'users/:id/edit_status' => 'users/registrations#edit_status', as: :edit_user_status
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :todo_lists, dependent: :destroy
  belongs_to :expert

  validates :title, presence: true, length: { maximum: 100 }
  validates :tag, presence: true, length: { maximum: 30 }
  validates :estimated_duration, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 } 
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    if current_user.is_expert?
      @campaign = current_user.specific.campaigns.new
      authorize! :write, @campaign
    end
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    if current_user.is_expert?
      @campaign = current_user.specific.campaigns.new(campaign_params)

      respond_to do |format|
        if @campaign.save
          format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
          format.json { render :show, status: :created, location: @campaign }
        else
          format.html { render :new }
          format.json { render json: @campaign.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:tag, :title, :estimated_duration)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign, local: true) do |form| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="field">
    <%= form.label :estimated_duration %>
    <%= form.number_field :estimated_duration %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <th>Title</th>
        <th>Tag</th>
        <th>Estimated Duration</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><%= campaign.title %></td>
        <td><%= campaign.tag %></td>
        <td><%= campaign.estimated_duration %></td>
        <td><%= link_to 'Show', campaign %></td>
        <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Create Todo List', new_todo_list_path(campaign_id: campaign.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_campaign_path %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<tr>
  <th>Title</th>
  <th>Tag</th>
  <th>Estimated Duration</th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
</tr>
<br />
<tr>
  <td>
    <%= @campaign.title %>
  </td>
  <td>
    <%= @campaign.tag %>
  </td>
  <td>
    <%= @campaign.estimated_duration %>
  </td>
  <td>
    <% @campaign.todo_lists.each do |todo_list| %>
      <li>Status: <%= todo_list.status %></li>
      <%= link_to('Go to TodoList', todo_list_path(todo_list)) %>
    <% end %>
  </td>
</tr>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>